apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hpgrahsl-dryrun-poi-map-app-dev
  annotations:
    argocd/app-name: hpgrahsl-dryrun-poi-map-app-dev
    backstage.io/kubernetes-id: hpgrahsl-dryrun-poi-map-app-dev
    backstage.io/kubernetes-namespace: hpgrahsl-dryrun
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=hpgrahsl-dryrun-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23DevLab/hpgrahsl-dryrun-map-app
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://devspaces.apps.summit23.0x74.p1.openshiftapps.com/#https://github.com/Summit23DevLab/hpgrahsl-dryrun-map-app?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:hpgrahsl"
  system: workshop-system-hpgrahsl-dryrun
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hpgrahsl-dryrun
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:hpgrahsl"
